Feature/tools improvements (#41)
cmonitor_chart:
* BACKWARD INCOMPATIBLE CHANGE: remove --input option in favour of more standard positional argument for input
* BACKWARD INCOMPATIBLE CHANGE: remove --filter option moved into new cmonitor_filter --task_name option
* add support for reading JSON directly from stdin using '-'
* add custom metadata in chart output under "Configuration"
* add commit hash into --version output
* refactoring to share code with other Python utils

cmonitor_statistics:
* BACKWARD INCOMPATIBLE CHANGE: remove --input option in favour of more standard positional argument for input
* add support for reading JSON directly from stdin using '-'
* add commit hash into --version output
* refactoring to share code with other Python utils

cmonitor_collector:
* add commit hash into --version output

others:
* add new cmonitor_filter utility that can be used as filtering stage before cmonitor_statistics or cmonitor_chart are used
* all components: bump to a 3digits version 2.3.0 plus release number for RPMs fixed to 0; this is to better match github tags

diff --git a/tools/Makefile b/tools/Makefile
--- a/tools/Makefile
+++ b/tools/Makefile
@@ -11,49 +11,62 @@ include $(ROOT_DIR)/Constants.mk
 
 TOOLS = \
 	chart/cmonitor_chart.py \
+	filter/cmonitor_filter.py \
 	statistics/cmonitor_statistics.py
+SYMLINKS = \
+	chart/cmonitor_chart \
+	filter/cmonitor_filter \
+	statistics/cmonitor_statistics
+COMMON_CODE = \
+	common-code/cmonitor_loader.py \
+	common-code/cmonitor_version.py
 
 #
 # BUILD TARGETS
 #
 
-all: $(TOOLS)
+all: $(TOOLS) 
+
+#$(SYMLINKS)
 
 clean:
-	rm -f $(TOOLS)
+	rm -f $(SYMLINKS)
 
 install: $(TOOLS)
+ifndef BINDIR
+	@echo "*** ERROR: please call this makefile supplying explicitly the BINDIR variable"
+	@exit 1
+endif
+ifndef PYTHON3_SITELIB
+	@echo "*** ERROR: please call this makefile supplying explicitly the PYTHON3_SITELIB variable"
+	@exit 1
+endif
 	@mkdir -p $(DESTDIR)/$(BINDIR)/
-	@cp -fv chart/cmonitor_chart.py             $(DESTDIR)/$(BINDIR)/cmonitor_chart
-	@cp -fv statistics/cmonitor_statistics.py   $(DESTDIR)/$(BINDIR)/cmonitor_statistics
-	chmod a+x $(DESTDIR)/$(BINDIR)/cmonitor_chart
-	chmod a+x $(DESTDIR)/$(BINDIR)/cmonitor_statistics
+	@for tool in $(SYMLINKS); do \
+		cp -fv $${tool}.py             $(DESTDIR)/$(BINDIR)/$$(basename $$tool) ; \
+		chmod a+x $(DESTDIR)/$(BINDIR)/$$(basename $$tool) ; \
+	done
+	@mkdir -p $(DESTDIR)/$(PYTHON3_SITELIB)/
+	cp -fv $(COMMON_CODE) $(DESTDIR)/$(PYTHON3_SITELIB)/
+
+test:
+	$(MAKE) -C filter    test
+	# FIXME:
+	# $(MAKE) -C chart         test
+	# $(MAKE) -C statistics    test
 
 # TOOLS
 
-chart/cmonitor_chart.py: chart/cmonitor_chart.py.j2
-	cp chart/cmonitor_chart.py.j2 chart/cmonitor_chart.py
-	sed -i 's@__RPM_VERSION__@$(CMONITOR_VERSION)@g' chart/cmonitor_chart.py
-	sed -i 's@__RPM_RELEASE__@$(CMONITOR_RELEASE)@g' chart/cmonitor_chart.py
-	chmod a+x chart/cmonitor_chart.py
+common-code/cmonitor_version.py: common-code/cmonitor_version.py.j2
+	cp common-code/cmonitor_version.py.j2 common-code/cmonitor_version.py
+	sed -i 's@__RPM_VERSION__@$(CMONITOR_VERSION)@g' common-code/cmonitor_version.py
+	sed -i 's@__RPM_RELEASE__@$(CMONITOR_RELEASE)@g' common-code/cmonitor_version.py
+	sed -i 's@__LAST_COMMIT_HASH__@$(CMONITOR_LAST_COMMIT_HASH)@g' common-code/cmonitor_version.py
 
-statistics/cmonitor_statistics.py: statistics/cmonitor_statistics.py.j2
-	cp statistics/cmonitor_statistics.py.j2 statistics/cmonitor_statistics.py
-	sed -i 's@__RPM_VERSION__@$(CMONITOR_VERSION)@g' statistics/cmonitor_statistics.py
-	sed -i 's@__RPM_RELEASE__@$(CMONITOR_RELEASE)@g' statistics/cmonitor_statistics.py
-	chmod a+x statistics/cmonitor_statistics.py
+$(TOOLS): common-code/cmonitor_version.py
 
-# TESTS
-
-TEST_KERNELS = \
-	centos7-Linux-3.10.0-x86_64 \
-	fedora35-Linux-5.14.17-x86_64 \
-	ubuntu20.04-Linux-5.4.0-x86_64
-
-test: chart/cmonitor_chart.py statistics/cmonitor_statistics.py 
-	for kk in $(TEST_KERNELS); do \
-		statistics/cmonitor_statistics.py --input=$(ROOT_DIR)/collector/src/tests/$$kk/expected-withthreads.json --output=tests/result-withthreads.json ; \
-	done
+#$(SYMLINKS): common-code/cmonitor_version.py
+#	@ln -sfv $(shell readlink -f $@.py) $@
 
 
 
@@ -71,6 +84,8 @@ srpm_tarball:
 	cp -arf $(ROOT_DIR)/ $(RPM_TARBALL_DIR)/ && \
 		cd $(RPM_TARBALL_DIR) && \
 		rm -rf cmonitor/examples && \
+		rm -rf cmonitor/collector/bin && \
+		rm -rf cmonitor/collector/src/tests && \
 		mv cmonitor cmonitor-tools-$(CMONITOR_VERSION) && \
 		sed -i 's@__RPM_VERSION__@$(CMONITOR_VERSION)@g' cmonitor-tools-$(CMONITOR_VERSION)/tools/spec/tools.spec && \
 		sed -i 's@__RPM_RELEASE__@$(CMONITOR_RELEASE)@g' cmonitor-tools-$(CMONITOR_VERSION)/tools/spec/tools.spec && \
